//! Offline provider. Lets the whole pipeline run end to end with no network
//! and no API key, which is how the smoke test and most integration tests work.
//!
//! It answers by role. Every prompt gitai builds carries a `gitai-role: <role>`
//! marker in its system turn, and the mock keys off that. Point `base_url` at a
//! directory of `<role>.txt` files to script the replies instead.

use std::path::PathBuf;
use std::time::Instant;

use async_trait::async_trait;
use gitai_core::config::ProviderConfig;
use gitai_core::error::Result;
use gitai_core::llm::{ChatRequest, ChatResponse, LlmProvider, Usage};

/// Marker gitai writes into every system prompt.
pub const ROLE_MARKER: &str = "gitai-role:";

pub struct MockProvider {
    name: String,
    script_dir: Option<PathBuf>,
}

impl MockProvider {
    pub fn new(name: impl Into<String>, cfg: &ProviderConfig) -> Self {
        let script_dir = if cfg.base_url.is_empty() || cfg.base_url.starts_with("http") {
            None
        } else {
            Some(PathBuf::from(&cfg.base_url))
        };
        Self {
            name: name.into(),
            script_dir,
        }
    }

    fn role_of(req: &ChatRequest) -> String {
        for m in &req.messages {
            if let Some(pos) = m.content.find(ROLE_MARKER) {
                let rest = &m.content[pos + ROLE_MARKER.len()..];
                let role = rest
                    .split(|c: char| c.is_whitespace())
                    .find(|s| !s.is_empty())
                    .unwrap_or("");
                if !role.is_empty() {
                    return role.to_string();
                }
            }
        }
        "unknown".into()
    }

    fn canned(role: &str) -> String {
        match role {
            "planner" => r#"{
  "goal": "Mock plan: satisfy the issue as literally as possible.",
  "acceptance": ["the described behaviour exists", "existing tests still pass"],
  "constraints": ["do not touch unrelated files"],
  "allowed_paths": [],
  "relevant_files": [],
  "test_plan": ["run the repository test suite"],
  "notes": "generated by the mock provider",
  "difficulty": 2
}"#
            .into(),
            // Writes one harmless file. An empty edit list would be valid JSON
            // but would fail the gate's "did anything change" check, so the
            // offline smoke test would never reach the review stages.
            "worker" => r#"{
  "reasoning": "mock worker leaves a marker so the run has something to review",
  "read": [],
  "edits": [
    {"op": "write", "path": "GITAI_SMOKE.md", "content": "Written by the gitai mock provider.\n"}
  ]
}"#
            .into(),
            "editor" => {
                r#"{"done": true, "notes": "mock editor is satisfied", "next_steps": []}"#.into()
            }
            "reviewer" | "arbiter" => r#"{
  "approved": true,
  "score": 75,
  "summary": "mock review: accepted without inspection",
  "blocking": [],
  "suggestions": []
}"#
            .into(),
            _ => "{}".into(),
        }
    }
}

#[async_trait]
impl LlmProvider for MockProvider {
    fn name(&self) -> &str {
        &self.name
    }

    async fn complete(&self, req: ChatRequest) -> Result<ChatResponse> {
        let started = Instant::now();
        let role = Self::role_of(&req);

        let content = match &self.script_dir {
            Some(dir) => std::fs::read_to_string(dir.join(format!("{role}.txt")))
                .unwrap_or_else(|_| Self::canned(&role)),
            None => Self::canned(&role),
        };

        Ok(ChatResponse {
            content,
            usage: Usage {
                prompt_tokens: (req.prompt_chars() / 4) as u64,
                completion_tokens: 64,
            },
            finish_reason: Some("stop".into()),
            model: req.model,
            latency_ms: started.elapsed().as_millis() as u64,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gitai_core::llm::ChatMessage;

    #[tokio::test]
    async fn answers_according_to_the_role_marker() {
        let p = MockProvider::new("mock", &ProviderConfig::default());
        let req = ChatRequest::new(
            "mock",
            vec![
                ChatMessage::system("you are a planner\ngitai-role: planner\n"),
                ChatMessage::user("do the thing"),
            ],
        );
        let resp = p.complete(req).await.unwrap();
        assert!(resp.content.contains("acceptance"), "{}", resp.content);
    }

    #[test]
    fn unmarked_prompts_fall_back_to_unknown() {
        let req = ChatRequest::new("m", vec![ChatMessage::user("hello")]);
        assert_eq!(MockProvider::role_of(&req), "unknown");
    }
}
